CREATE DATABASE ProyectoFinalIngSoft
GO

USE ProyectoFinalIngSoft
GO

CREATE TABLE SystemUsers
(
	LogInUser varchar(15) NOT NULL,
	Clave varchar (15) NOT NULL,
	CONSTRAINT PK_loginuser PRIMARY KEY (LogInUser)
)
GO

CREATE TABLE UserStories (
	USId int identity(1,1) PRIMARY KEY,
	Nombre varchar(20) NOT NULL,
	Descripcion varchar(50) NOT NULL,
	Prioridad int NOT NULL,
	Estado varchar(15) NOT NULL
)
GO

INSERT INTO SystemUsers(LogInUser, Clave) VALUES
('genesis', 123),
('dayanac', 456),
('dayannal', 789)
GO

CREATE PROCEDURE VALIDAR_USUARIO
@loginuser varchar(15),
@clave varchar(15)

	As
		Begin
			Select LogInUser, Clave  
			FROM SystemUsers 
			WHERE LogInUser = @loginuser and Clave = @clave
		End
GO

CREATE PROCEDURE INSERTAR_SYSTEMUSERS
@LOGINUSER VARCHAR(15),
@CLAVE VARCHAR(15)
 AS 
	BEGIN
		INSERT INTO SystemUsers(LogInUser, Clave) VALUES (@LOGINUSER, @CLAVE)
	END
GO

CREATE PROCEDURE BORRAR_SYSTEMUSERS
@LOGINUSER INT
 AS
	BEGIN
	  DELETE SystemUsers WHERE LogInUser = @LOGINUSER
END
GO

CREATE PROCEDURE CONSULTAR_SYSTEMUSERS_ID
@LOGINUSER INT
 AS
	BEGIN
	  SELECT * FROM SystemUsers WHERE LogInUser = @LOGINUSER
	END
GO

CREATE PROCEDURE ACTUALIZAR_SYSTEMUSERS
@LOGINUSER INT,
@CLAVE VARCHAR(15)
AS
	BEGIN
		UPDATE SystemUsers SET Clave = @CLAVE WHERE LogInUser = @LOGINUSER
	END
GO

--User stories

CREATE PROCEDURE INSERTAR_USERSTORIES
@NOMBRE VARCHAR(15),
@DESCRIPCION VARCHAR(15),
@PRIORIDAD INT,
@ESTADO VARCHAR(15)
 AS 
	BEGIN
		INSERT INTO UserStories(Nombre, Descripcion, Prioridad, Estado) VALUES (@NOMBRE, @DESCRIPCION, @PRIORIDAD, @ESTADO)
	END
GO

CREATE PROCEDURE BORRAR_USERSTORIES
@USID INT
 AS
	BEGIN
	  DELETE UserStories WHERE USId = @USID
END
GO

CREATE PROCEDURE CONSULTAR_USERSTORIES_ID
@USID INT
 AS
	BEGIN
	  SELECT * FROM UserStories WHERE USId = @USID
	END
GO

CREATE PROCEDURE ACTUALIZAR_USERSTORYID
@NOMBRE VARCHAR(20),
@DESCRIPCION VARCHAR(50),
@PRIORIDAD INT,
@ESTADO VARCHAR(15),
@USID int
AS
	BEGIN

		UPDATE UserStories SET Nombre = @Nombre, Descripcion = @DESCRIPCION, Prioridad = @PRIORIDAD, Estado = @ESTADO WHERE USId=@USID

	END
GO

CREATE PROCEDURE ACTUALIZAR_USERSTORYESTADOID
@ESTADO VARCHAR(15),
@USID int
AS
	BEGIN
		UPDATE UserStories SET Estado = @ESTADO WHERE USId=@USID
	END
GO

CREATE PROCEDURE CONSULTAR_US_ESTADO
@ESTADO VARCHAR
 AS
	BEGIN
	  SELECT * FROM UserStories WHERE Estado = @ESTADO
	END
GO

CREATE PROCEDURE CONSULTAR_US
 AS
	BEGIN
	  SELECT * FROM UserStories
	END
GO


SELECT * FROM UserStories

INSERT INTO UserStories(Nombre, Descripcion, Prioridad, Estado) VALUES ('TestUS3', 'Lorem ipsum test3', 2, 'WIP')